version: "3"


networks:
  backend:
    external: true 


services:
  betanin:
    image: sentriz/betanin
    # ports:
    #   - 9393:9393
    restart: unless-stopped
    environment:
      - UID=0 # (optionally) set user id
      - GID=0 # (optionally) set group id
    volumes:
      - ${DATA}/betanin/data:/b/.local/share/betanin/
      - ${DATA}/betanin/config:/b/.config/betanin/
      - ${DATA}/betanin/beets:/b/.config/beets/
      - ./config/beets.yml:/b/.config/beets/config.yaml
      # Music library
      - ${MEDIA}/00music:/music
      # qbittorrent path
      - ${MEDIA}/00download:/downloads
      # - ${MEDIA}/00music:/downloads
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"