---
- name: Generate Homer Jinja2 template
  hosts: localhost
  gather_facts: false

  vars_files:
    # - vars/main.yml
    - vars/apps.yml
    - vars/homer.yml
    - vars/secrets.yml


  tasks:
    - name: Generate Jinja2 template
      ansible.builtin.template:
        src: files/config-homer.jinja2
        dest: docker-compose/docker-compose-homer/config/config-homer.yml
