---
  
- name: Upload config
  hosts: local-1
  become: true
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  tasks:
    # Traefik configuration
  - name: Create "/etc/traefik" directory
    file:
      path: /opt/traefik/certs
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Upload traefik.yml static config to server
    # copy:
    template:
      # src: files/traefik.yml
      src: files/traefik.yml.j2
      dest: /opt/traefik/traefik.yml
      mode: 0644
      owner: root
      group: root
    notify: "Restart Traefik"

  ### AUTHELIA CONFIG ###
  - name: Upload AUTHELIA static config to server
    # copy:
    template:
      # src: files/authelia-conf.yml
      src: files/authelia-conf.yml.j2
      dest: /opt/authelia/configuration.yml
      mode: 0600
      owner: root
      group: root
    notify: "Restart Authelia"


  - name: Upload AUTHELIA static user DB
    copy: 
      src: files/authelia-users_database.yml
      dest: /etc/authelia/users_database.yml
      mode: 0600
      owner: root
      group: root
    notify: "Restart Authelia"

  handlers:
    - include: handlers/handlers.yml