---
  
- name: Upload traefik.yml config
  hosts: local-1
  become: true

  tasks:
    # Traefik configuration
  - name: Create "/etc/traefik" directory
    file:
      path: /opt/traefik/certs
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Upload traefik.yml static config to server
    copy: 
      src: files/traefik.yml
      dest: /opt/traefik/traefik.yml
      mode: 0644
      owner: root
      group: root

  # - name: Upload config.yml static config to server
  #   copy: 
  #     src: files/traefik.yml
  #     dest: /opt/traefik/traefik.yml
  #     mode: 0644
  #     owner: root
  #     group: root

    # Certificate files config
  - name: Upload certificate file for traefik
    copy:
      src: files/domain.cert
      dest: /opt/traefik/certs/domain.cert
      mode: 0644
      owner: root
      group: root
      # state: directory

  - name: Upload certificate KEY file for traefik
    copy:
      src: files/domain.key
      dest: /opt/traefik/certs/domain.key
      mode: 0600
      owner: root
      group: root
      # state: directory

  ### AUTHELIA CONFIG ###
  # - name: Create "/opt/authelia" directory
  #   file:
  #     path: /etc/traefik/certs
  #     state: directory
  #     mode: 0755
  #     owner: root
  #     group: root


  - name: Upload AUTHELIA static config to server
    copy: 
      src: files/authelia-conf.yml
      dest: /opt/authelia/configuration.yml
      mode: 0600
      owner: root
      group: root


  - name: Upload AUTHELIA static user DB
    copy: 
      src: files/authelia-users_database.yml
      dest: /opt/authelia/users_database.yml
      mode: 0600
      owner: root
      group: root
