- hosts: local-1
  become: yes
  # become_user: ansible
  vars_files:
    - vars/main.yml
    - vars/apps.yml
    - vars/secrets.yml
  ignore_errors: "{{ ansible_check_mode }}"
  gather_facts: no

  tasks:
    - name: configure authelia
      include_tasks: tasks/config-authelia.yml

  # roles:
    # - role: docker-compose # Configure docker apps  
    # - role: mount-ext-hdd
    # - role: samba
    # - role: create-symlinks # Configure symlinks for Compose
      # prod_apps:
      #   - name: traefik



  handlers:
    - include: handlers/handlers.yml