---
version: "3"

networks:
  backend:
    external: true

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    command:
      # https://dev.to/cloudx/taming-cadvisors-high-cpu-usage-1nm5
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      # https://github.com/google/cadvisor/issues/3139
      - "--disable_metrics=percpu,sched,disk,diskIO,cpu_topology,referenced_memory"
    # ports:
    #   - 8080:8080
    expose:
      - 8080
    # network_mode: host
    networks:
      - backend
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'
    privileged: true
    restart: always