---

networks:
  backend:
    external: true


version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:v0.21.1873-ls321
    container_name: jackett
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/Warsaw
      - AUTO_UPDATE=false #optional
      # - AUTO_UPDATE=true #optional
      # - RUN_OPTS= #optional
    volumes:
      - /opt/jackett:/config
      # - /path/to/blackhole:/downloads
    # ports:
    #   - 9117:9117
    networks:
      - backend 
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '512M'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      # https://doc.traefik.io/traefik/middlewares/http/stripprefix/
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
      # scopes: autoupdate, monitor
      - com.centurylinklabs.watchtower.scope=autoupdate
      # - com.centurylinklabs.watchtower.monitor-only="true"
      # Homer labels
      - "homer.enable=true"
      - "homepage.group=Downloading"
      - "homepage.name=Jackett"
      - "homepage.description=API Support for your favorite torrent trackers "
      - "homepage.icon=jackett.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"