---
networks:
  backend:
    external: true


version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=2000
      - PGID=2000
      # - TZ=Europe/London
      - TZ=Etc/UTC
    volumes:
      - /opt/readarr:/config
      # - /path/to/books:/books #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
      - /mnt/myhdd/readarr-dl:/downloads
    # ports:
    #   - 8787:8787
    networks:
      - backend 
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      # https://doc.traefik.io/traefik/middlewares/http/stripprefix/
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"

