# https://medium.com/@ugenef/application-monitoring-with-traefik-prometheus-grafana-and-docker-compose-for-beginners-2fe25d1b60a8
version: "3.3"
networks:
  backend:
    external: true

services:
  prometheus:
    image: prom/prometheus
    user: root # https://stackoverflow.com/questions/74810089/err-open-prometheus-queries-active-permission-denied
    # environment: &env
    #   TRAEFIK_USERNAME: 'traefik'
    #   TRAEFIK_PASSWORD: 'traefik2020'
    container_name: "prometheus"
    volumes: 
      - "./config/prometheus/:/etc/prometheus"
      - "/opt/prometheus:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'
      - --storage.tsdb.retention.time=21d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      # - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      # - "traefik.http.routers.${SERVICE_NAME}.middlewares=traefik-auth"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
