---
- name: Copy Backup Script to Root's Home Directory
  copy:
    src: backup_script.sh  # Replace with the actual path to your backup script
    dest: /root/backup_script.sh
    mode: '0755'


- name: Check if /mnt/path Folder Exists
  stat:
    path: /mnt/path
  register: mnt_path_check


- name: Fail Playbook if /mnt/path Doesn't Exist
  fail:
    msg: "/mnt/path does not exist. Backup cannot proceed."
  when: not mnt_path_check.stat.exists


- name: Check if Backup Destination Exists
  stat:
    path: /mnt/path/backup/destination  # Replace with the actual path of your backup destination
  register: destination_check


- name: Create Backup Directory if It Doesn't Exist
  file:
    path: /mnt/path/backup/destination  # Replace with the actual path of your backup destination
    state: directory
  when: not destination_check.stat.exists


- name: Install Cron Job for Daily Backup
  cron:
    name: Weekly Backup
    minute: "0"
    hour: "3"  # Adjust the hour to your preferred backup time
    weekday: "6"  # Set to 6 to run on Saturday (0=Sunday, 1=Monday, ..., 6=Saturday)
    user: root
    # job: /root/backup_script.sh  # Path to your backup script
    job: "/path/to/backup_script.sh {{ source_directory }} {{ backup_destination }} {{ log_file }}"
    state: present
  vars:
    source_directory: "/path/to/source/directory"
    backup_destination: "/mnt/path/backup/destination"
    log_file: "/path/to/log/backup.log"  # Replace with the actual path for the log file

