---
version: "3"


networks:
  backend:
    external: true 


services:
  semaphore:
    image: semaphoreui/semaphore:v2.9.45
    container_name: semaphore
    # Custom user
    user: root
    volumes:
      - /opt/semaphore/home:/etc/semaphore # config.json location
      - /opt/semaphore/lib:/var/lib/semaphore # database.boltdb location (Not required if using mysql or postgres)
      - /srv/docker-compose/n8n/_playbooks:/files/playbooks
    restart: always
    networks:
      - backend
    ### Seucrity ###
    # cap_add:
    #   - CAP_NET_ADMIN
    # security_opt:
    #   - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'
    ## Env vars ####
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: ${PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: ${ADMIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
      # Watchtower
      # - com.centurylinklabs.watchtower.enable=true
      # scopes: autoupdate, monitor
      # - com.centurylinklabs.watchtower.scope=autoupdate
      # Homer labels
      - "homer.enable=true"
      - "homepage.group=Tools"
      - "homepage.name=Ansible Semaphore"
      - "homepage.description=Modern UI for Ansible."
      - "homepage.icon=semaphore.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"