---
version: "2.1"

networks:
  endlessh-only:
    driver: bridge

services:
  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: endlessh
    user: 2000:2000
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Etc/UTC
      - MSDELAY=10000 #optional
      - MAXLINES=32 #optional
      - MAXCLIENTS=4096 #optional
      - LOGFILE=false #optional
      - BINDFAMILY= #optional
    # volumes:
    #   - /path/to/appdata:/config #optional
    ports:
      - 22:2222
    restart: unless-stopped
    networks:
      - endlessh-only