---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /opt/calibre-web/config:/config
      - /media/books:/books
    #ports:
    #  - 8083:8083
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre-web.rule=Host(`books.europa.local`)"
      - "traefik.http.services.calibre-web.loadbalancer.server.port=8083"
      # - "traefik.docker.network=frontend"
      # - "traefik.http.routers.calibre-web.entrypoints=web"
      - "traefik.http.routers.calibre-web.tls=true"
      - traefik.http.routers.calibre-web.middlewares=authelia@docker


networks:
  frontend:
    external: true
