# https://www.reddit.com/r/selfhosted/comments/kvesf3/authelia_and_bitwarden_via_traefik/
# https://github.com/dani-garcia/vaultwarden/discussions/2934


# Docker Traefik ModSecurity Setup
# https://github.com/dani-garcia/vaultwarden/wiki/Docker---Traefik---ModSecurity-Setup


# NOTE:
# "I have a bitwarden instance running and I can confirm that the app will not connect if there is an issue with the certificate, either self signed or expired."
# https://www.reddit.com/r/selfhosted/comments/rip3z1/vaultwarden_bitwarden_app_failed_to_fetch_error/
version: '3.9'

networks:
  frontend:
    external: true 

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    user: 2000:2000
    environment:
      - WEBSOCKET_ENABLED=true
      #- SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - DOMAIN=https://vault.europa.local
      #- ADMIN_TOKEN=
    volumes:
      - /opt/vaultwarden:/data
    networks:
      - frontend
    labels:
      - traefik.enable=true
      # UI
      - traefik.http.routers.vaultwarden-ui.tls=true
      - traefik.http.routers.vaultwarden-ui.entrypoints=https
      - traefik.http.routers.vaultwarden-ui.rule=Host(`vault.europa.local`)
      - traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui
      - traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80
      # Websocket
      - traefik.http.routers.vaultwarden-websocket.tls=true
      - traefik.http.routers.vaultwarden-websocket.entrypoints=https
      - traefik.http.routers.vaultwarden-websocket.rule=Host(`vault.europa.local`) && Path(`/notifications/hub`)
      - traefik.http.routers.vaultwarden-websocket.service=vaultwarden-websocket
      - traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012
      # Middlewares
      # - traefik.http.routers.vaultwarden-ui.middlewares=chain-authelia@file
      - "traefik.http.routers.vaultwarden-ui.middlewares=authelia@docker"