version: '3.5'

networks:
  frontend:
    external: true 

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 2000:2000
    # environment:
    #   - PUID=2000
    #   - PGID=2000
    #   - TZ=Etc/UTC
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      # - /path/to/tvseries:/data/tvshows
      - /media/movies:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`media.europa.local`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.middlewares=authelia@docker"