version: '3'

networks:
  frontend:
    external: true


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - "8000:80"
    # expose:
    #   - 80
    labels:
      - "traefik.enable=true"
      # With this setup, when a request comes to Traefik with a path like /api/app/lol/1, Traefik will strip the /api prefix before forwarding the request to the app service
      # defines the routing rule to match requests with a path prefix
      - "traefik.http.routers.app.rule=Host(`traefik.europa.local`) && PathPrefix(`/testapp`)"
      # associates the stripprefix middleware with the app router
      - "traefik.http.routers.app.middlewares=stripprefix,authelia@docker"
      # configures the stripprefix middleware to remove the "/testapp" prefix from the incoming request
      - "traefik.http.middlewares.stripprefix.stripprefix.prefixes=/testapp"      
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.http.routers.app.tls=true"
      # - "traefik.http.routers.app.middlewares=authelia@docker"
    networks:
      - frontend


