# https://github.com/n8n-io/n8n/tree/master/docker/compose/withMariaDB

version: '3.8'

# volumes:
    # db_storage:
    # n8n_storage:


services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    # user: 2000:2000
    # environment:
    #   - DB_TYPE=mariadb
    #   - DB_MYSQLDB_HOST=db
    #   - DB_MYSQLDB_DATABASE=${MARIADB_DATABASE}
    #   - DB_MYSQLDB_USER=${MARIADB_USER}
    #   - DB_MYSQLDB_PASSWORD=${MARIADB_PASSWORD}
    #ports:
    #  - 5678:5678
    # links:
    #   - db
    volumes:
      - /opt/n8n:/files
    command: n8n start --tunnel
    # depends_on:
    #   db:
    #     condition: service_healthy
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.europa.local`)"
      # Sadly path-based routing doesn't work, issues with CSS/JS assets
      # - "traefik.http.routers.n8n.rule=Host(`app.europa.local`) && PathPrefix(`/n8n`)"
      # configures the stripprefix middleware to remove the prefix from the incoming request
      # - "traefik.http.middlewares.stripprefix-n8n.stripprefix.prefixes=/n8n"
      # https://stackoverflow.com/questions/58645726/vuejs-relative-resources-doesnt-work-behind-reverse-proxy
      # - "traefik.http.middlewares.test-redirectregex.redirectregex.regex=^(https|http)://([a-zA-Z0-9_.-]+)/([a-zA-Z0-9_.-]+)$$"
      # - "traefik.http.middlewares.test-redirectregex.redirectregex.replacement=$${1}://$${2}/$${3}/"
      # - "traefik.http.routers.n8n.middlewares=test-redirectregex,authelia@docker,stripprefix-n8n"
      # - "traefik.http.routers.n8n.middlewares=authelia@docker,stripprefix-n8n"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.middlewares=authelia@docker"

networks:
  frontend:
    external: true
