version: "3"

networks:
  frontend:
    external: true 

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # user: 2000:2000
    # ports:
    #   - 9443:9443
    volumes:
      - /opt/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      # With this setup, when a request comes to Traefik with a path like /api/app/lol/1, Traefik will strip the /api prefix before forwarding the request to the app service
      # defines the routing rule to match requests with a path prefix
      - "traefik.http.routers.portainer.rule=Host(`app.europa.local`) && PathPrefix(`/portainer`)"
      # associates the stripprefix middleware with the portainer router
      - "traefik.http.routers.portainer.middlewares=stripprefix-portainer,authelia@docker"
      # configures the stripprefix middleware to remove the prefix from the incoming request
      - "traefik.http.middlewares.stripprefix-portainer.stripprefix.prefixes=/portainer"      
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls=true"
      # - "traefik.http.routers.portainer.middlewares=authelia@docker"