version: '3.5'

networks:
  backend:
    external: true 

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # depends_on:
    #   - traefik
    #   - authelia
    security_opt:
      - no-new-privileges:true
    user: 2000:2000
    # environment:
    #   - PUID=2000
    #   - PGID=2000
    #   - TZ=Etc/UTC
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      # - /path/to/tvseries:/data/tvshows
      - /media/movies:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - backend
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --fail http://jellyfin:${PORT}/ || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"