version: "3"

networks:
  backend:
    external: true

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: always
    # ports:
    #   - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
    volumes:
      - "/opt/navidrome:/data"
      # - "/path/to/your/music/folder:/music:ro"
      - "/mnt/myhdd/Muzyka_DB2:/music:ro"
    deploy:
      resources:
        limits:
          # Adjust as needed
          cpus: '0.2'
          memory: '512M'
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
      # Homer labels
      - "homer.enable=true"
      - "homepage.group=Media & Fun"
      - "homepage.name=Navidrome"
      - "homepage.description=Open source web-based music collection server and streamer."
      - "homepage.icon=navidrome.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"