---

networks:
  backend:
    external: true


version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Etc/UTC
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER= #optional
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - /opt/transmission:/config
      # - /path/to/downloads:/downloads
      # - /path/to/watch/folder:/watch
    networks:
      - backend 
    ports:
      # - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      # https://doc.traefik.io/traefik/middlewares/http/stripprefix/
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - 'traefik.http.routers.${SERVICE_NAME}.tls.certresolver=duckdns'
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"


