---
version: "3"


networks:
  backend:
    external: true 

# Hardening source: https://www.linode.com/content/hackersploit-docker-security-essentials-ebook/

# TO ADD:
# PREVENTING PRIVILEGE ESCALATION ATTACKS
# docker run --security-opt=no-new-privileges <IMAGE-ID>
# The no-new-privileges option will stop container processes from gaining any additional privileges.
# LIMITING CONTAINER CAPABILITIES
# You also can run a container with the --privileged flag, which gives it all of the kernel capability options.
#  However, this is never recommended 
# We can remove all kernel capabilities when running a container with the following options:
# docker run --cap-drop all <IMAGE-ID>
# 2. You can also add the specific kernel capabilities required by your containers by running the following command:
# docker run --cap-drop all --cap-add <CAPABILITY> <IMAGE-ID>

services:
  ntfy:
    image: binwiederhier/ntfy:v2.8.0
    container_name: ntfy
    # For custom Docker user
    # build:
    #   context: "."
    #   target: "app"
    #   args:
    #     - "UID=${UID:-2000}"
    #     - "GID=${GID:-2000}"
    user: 2000:2000
    volumes:
      # Ensure proper timezones
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Other required paths - per app
      - ${DATA}/ntfy/cache:/var/cache/ntfy
      - ${DATA}/ntfy/etc:/etc/ntfy
    restart: always
    networks:
      - backend
    command:
      - serve
    ### Seucrity ###
    # cap_add:
    #   - CAP_NET_ADMIN
    # security_opt:
    #   - seccomp:unconfined
    deploy:
      resources:
        limits:
          # Adjust as needed
          cpus: '0.1'
          memory: '256M'
    # environment:
    #   - ENV:VAR
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
      # Watchtower
      # - com.centurylinklabs.watchtower.enable=true
      # scopes: autoupdate, monitor
      # - com.centurylinklabs.watchtower.scope=autoupdate
      # Homer labels
      - "homer.enable=true"
      - "homepage.group=Tools"
      - "homepage.name=ntfy.sh"
      - "homepage.description=Send push notifications to your phone or desktop using PUT/POST"
      - "homepage.icon=ntfy.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"