---
version: "3"


networks:
  backend:
    external: true 

# Hardening source: https://www.linode.com/content/hackersploit-docker-security-essentials-ebook/

# TO ADD:
# PREVENTING PRIVILEGE ESCALATION ATTACKS
# docker run --security-opt=no-new-privileges <IMAGE-ID>
# The no-new-privileges option will stop container processes from gaining any additional privileges.
# LIMITING CONTAINER CAPABILITIES
# You also can run a container with the --privileged flag, which gives it all of the kernel capability options.
#  However, this is never recommended 
# We can remove all kernel capabilities when running a container with the following options:
# docker run --cap-drop all <IMAGE-ID>
# 2. You can also add the specific kernel capabilities required by your containers by running the following command:
# docker run --cap-drop all --cap-add <CAPABILITY> <IMAGE-ID>

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.8
    container_name: homepage
    volumes:
      # Ensure proper timezones
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Docker Socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Other required paths - per app
      - /opt/homepage:/app/config
    restart: always
    networks:
      - backend
    ### Seucrity ###
    # cap_add:
    #   - CAP_NET_ADMIN
    # security_opt:
    #   - seccomp:unconfined
    deploy:
      resources:
        limits:
          # Adjust as needed
          cpus: '0.2'
          memory: '250M'
    environment:
      - PUID=0
      - PGID=0


    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # redirection
      - "traefik.http.middlewares.redirect-middleware.redirectregex.regex=^https://${ROOT_DOMAIN}/(.*)"
      - "traefik.http.middlewares.redirect-middleware.redirectregex.replacement=https://${SUBDOMAIN}.${ROOT_DOMAIN}/$$1"
      - "traefik.http.middlewares.redirect-middleware.redirectregex.permanent=true"
      - "traefik.http.middlewares.redirect-middleware.priority=5"

      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=redirect-middleware@docker,authelia@docker"
      # Watchtower
      # - com.centurylinklabs.watchtower.enable=true
      # scopes: autoupdate, monitor
      # - com.centurylinklabs.watchtower.scope=autoupdate
      # Homer labels
      # - "homer.enable=true"
      # - "homepage.group=Tools"
      # - "homepage.name=http-echo"
      # - "homepage.description=http-echo server"
      # - "homepage.icon=nginx.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"