# ---
# - name: Update packages
#   hosts: localhost
#   become: true
#   tasks:
#     - name: apt
#       apt:
#         update_cache: yes
#         upgrade: 'yes'


# Experimental
---
- name: Update packages
  hosts: localhost
  become: true
  tasks:
    - name: Update package information
      apt:
        update_cache: yes
      register: apt_update

    - name: Check if any packages need update
      shell: apt list --upgradable | grep -c 'upgradable'
      register: upgradable_count
      changed_when: false
    
    - name: Output up-to-date message
      debug:
        msg: "All packages are up to date."
      when: upgradable_count.stdout == "0"


    - name: Output count of packages to update
      debug:
        msg: "Count of packages to update: {{ upgradable_count.stdout }}"
      when: upgradable_count.stdout != "0"


    - name: Store information about upgradable packages
      shell: apt list --upgradable
      register: upgradable_packages
      when: upgradable_count.stdout != "0"

    - name: Parse upgradable packages
      set_fact:
        upgraded_package_names: "{{ upgradable_packages.stdout_lines | map('regex_replace', '^(\\S+).+', '\\1') | list }}"
      when: upgradable_count.stdout != "0"

    - name: Display upgradable package names
      debug:
        var: upgraded_package_names
      when: upgradable_count.stdout != "0"

    - name: Upgrade all packages
      apt:
        # upgrade: dist
        name: "*"
        # autoremove: yes
        state: latest
      when: apt_update.changed
