---
version: "2.1"

networks:
  backend:
    external: true

services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Etc/UTC
    volumes:
      - /opt/pyload:/config
      - /mnt/myhdd/pyload-dl:/downloads
    # ports:
    #   - 8000:8000 # Webinterface
    #   - 9666:9666 # Click 'N' Load
    restart: unless-stopped
    networks:
      - backend 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      # https://doc.traefik.io/traefik/middlewares/http/stripprefix/
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"

