---
version: "3"

networks:
  backend:
    external: true

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: always
    # depends_on:
    #   - traefik
    #   - authelia
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${DATA}/calibre-web/config:/config
      # - /media/books:/books
      - "${MEDIA}/00_Backup_random/Losowe książki:/books"
    #ports:
    #  - 8083:8083
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      # - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker
        # Homer labels
      - "homer.enable=true"
      - "homer.service=Media & Fun"
      - "homer.name=Calibre Web"
      - "homer.subtitle=Calibre Web server"
      - "homer.logo=icons/calibreweb.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homer.url=https://${SUBDOMAIN}.${ROOT_DOMAIN}"