---
version: "3"

networks:
  backend:
    external: true


services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # depends_on:
    #   - traefik
    #   - authelia
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - "/opt/qbittorrent:/config"
      - "/media/download:/downloads"
    ports:
    # - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - backend 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      # https://doc.traefik.io/traefik/middlewares/http/stripprefix/
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"


