version: '3.5'

services:
  coredns:
    image: coredns/coredns:1.10.1
    container_name: coredns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config/Corefile:/etc/coredns/Corefile
    restart: always
