---
version: "3.7"


networks:
  backend:
    external: true 

# Hardening source: https://www.linode.com/content/hackersploit-docker-security-essentials-ebook/

# TO ADD:
# PREVENTING PRIVILEGE ESCALATION ATTACKS
# docker run --security-opt=no-new-privileges <IMAGE-ID>
# The no-new-privileges option will stop container processes from gaining any additional privileges.
# LIMITING CONTAINER CAPABILITIES
# You also can run a container with the --privileged flag, which gives it all of the kernel capability options.
#  However, this is never recommended 
# We can remove all kernel capabilities when running a container with the following options:
# docker run --cap-drop all <IMAGE-ID>
# 2. You can also add the specific kernel capabilities required by your containers by running the following command:
# docker run --cap-drop all --cap-add <CAPABILITY> <IMAGE-ID>

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.7.2
    container_name: audiobookshelf
    # For custom Docker user
    # build:
    #   context: "."
    #   target: "app"
    #   args:
    #     - "UID=${UID:-2000}"
    #     - "GID=${GID:-2000}"
    # user: dockeruser
    volumes:
      # Ensure proper timezones
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Other required paths - per app
      # These volumes are needed to keep your library persistent
      # and allow media to be accessed by the ABS server.
      # The path to the left of the colon is the path on your computer,
      # and the path to the right of the colon is where the data is
      # available to ABS in Docker.
      # You can change these media directories or add as many as you want
      - ${MEDIA}/audiobooks:/audiobooks
      - ${MEDIA}/podcasts:/podcasts
      # The metadata directory can be stored anywhere on your computer
      - /opt/audiobookshelf/metadata:/metadata
      # The config directory needs to be on the same physical machine
      # you are running ABS on
      - /opt/audiobookshelf/config:/config
    restart: always
    networks:
      - backend
    ### Seucrity ###
    # cap_add:
    #   - CAP_NET_ADMIN
    # security_opt:
    #   - seccomp:unconfined
    deploy:
      resources:
        limits:
          # Adjust as needed
          cpus: '0.2'
          memory: '512M'
    environment:
      # - ENV:VAR
       - user=${UID}:${GID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker,secured@file"
      # Watchtower
      # - com.centurylinklabs.watchtower.enable=true
      # scopes: autoupdate, monitor
      # - com.centurylinklabs.watchtower.scope=autoupdate
      # Homer labels
      - "homer.enable=true"
      - "homepage.group=Media & Fun"
      - "homepage.name=Audiobookshelf"
      - "homepage.description=Audiobookshelf is a self-hosted audiobook and podcast server."
      - "homepage.icon=audiobookshelf.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"