version: '3.7'


networks:
  backend:
    external: true 


services:
  watchtower-monitor:
    container_name: watchtower-monitor
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 8080:8080
    expose:
      - 8080
    # command: --interval 10 --http-api-metrics --http-api-token demotoken --debug prometheus grafana parent child
    # cron syntax: https://pkg.go.dev/github.com/robfig/cron@v1.2.0#hdr-CRON_Expression_Format
    command: --scope monitor --schedule "0 0 4 * * SAT"
    environment:
      # Will only monitor for new images, send notifications and invoke the pre-check/post-check hooks, but will not update the containers.
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_LABEL_ENABLE=true
      # Gotify notifications
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://gotify:80/
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${GOTIFY_TOKEN_MONITOR}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
    labels:
      # Multiple instances: https://containrrr.dev/watchtower/running-multiple-instances/ 
      - "com.centurylinklabs.watchtower.scope=monitor"
    networks:
      - backend
      
  
  watchtower-restart:
    container_name: watchtower-restart
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 8080:8080
    expose:
      - 8080
    # command: --interval 10 --http-api-metrics --http-api-token demotoken --debug prometheus grafana parent child
    # cron syntax: https://pkg.go.dev/github.com/robfig/cron@v1.2.0#hdr-CRON_Expression_Format
    command: --schedule "0 0 4 * * SAT" --scope autoupdate
    environment:
      # Will only monitor for new images, send notifications and invoke the pre-check/post-check hooks, but will not update the containers.
      # - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_LABEL_ENABLE=true
      # Gotify notifications
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://gotify:80/
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${GOTIFY_TOKEN_AUTO}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
    labels:
      # Multiple instances: https://containrrr.dev/watchtower/running-multiple-instances/ 
      - "com.centurylinklabs.watchtower.scope=autoupdate"
    networks:
      - backend
      