# https://github.com/n8n-io/n8n/tree/master/docker/compose/withMariaDB

version: '3.8'

# volumes:
#   config-folder:
#     driver_opts:
#         # type: "nfs"
#         # o: "addr=10.40.0.199,nolock,soft,rw"
#         device: "/opt/n8n"

networks:
  backend:
    external: true

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    # depends_on:
    #   - traefik
    #   - authelia
    security_opt:
      - no-new-privileges:true    
    restart: unless-stopped
    # user: 2000:2000
    # environment:
    #   - DB_TYPE=mariadb
    #   - DB_MYSQLDB_HOST=db
    #   - DB_MYSQLDB_DATABASE=${MARIADB_DATABASE}
    #   - DB_MYSQLDB_USER=${MARIADB_USER}
    #   - DB_MYSQLDB_PASSWORD=${MARIADB_PASSWORD}
    #ports:
    #  - 5678:5678
    # links:
    #   - db
    volumes:
      - /opt/n8n:/files
    command: n8n start --tunnel
    # depends_on:
    #   db:
    #     condition: service_healthy
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"


