---
networks:
  backend:
    external: true


version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=2000
      - PGID=2000
      # - TZ=Europe/London
      - TZ=Etc/UTC
    volumes:
      - /opt/syncthings/config:/config
      # - /path/to/data1:/data1
      # - /path/to/data2:/data2
    ports:
      # - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - backend 
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      # https://doc.traefik.io/traefik/middlewares/http/stripprefix/
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"

