# Grafana setup
# https://medium.com/@ugenef/application-monitoring-with-traefik-prometheus-grafana-and-docker-compose-for-beginners-2fe25d1b60a8
version: "3.3"

networks:
  backend:
    external: true


services:
  headphones:
    image: lscr.io/linuxserver/headphones:latest
    container_name: "headphones"
    # depends_on:
    #   - prometheus
    volumes:
      # - /path/to/appdata/config:/config
      - /opt/headphones:/config
      # - /path/to/downloads:/downloads
      # - /path/to/music:/music
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Etc/UTC
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.service=headphones"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
    networks:
      - backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: "10m"
        max-file: "3"  