---
networks:
  frontend:
    external: true

version: "2"
services:
  homer:
    image: b4bz/homer:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /opt/homer:/www/assets
      - ./icons/png:/www/icons
      - ./config/config-homer.yml:/www/assets/config.yml
    # ports:
    #   - 8080:8080
    user: root # default
    environment:
      - INIT_ASSETS=1 # default
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '128M'
    networks:
      # - frontend
      - frontend
    labels:
      # Enable traefik for that container
      - "traefik.enable=true"
      # Create routing rules
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker,secured@file"
  homer-service-discovery:
    image: ghcr.io/calvinbui/homer-service-discovery:latest
    container_name: homer-service-discovery
    volumes:
      - ./config/config-homer.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For Homer autodiscovery by label
      - ./base.yml:/base.yml
    restart: always



# version: '3'
# services:
