---
version: "3"


networks:
  backend:
    external: true 



services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11
    container_name: uptime-kuma
    volumes:
      # Ensure proper timezones
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Other required paths - per app
      - /opt/uptime-kuma:/app/data
      # For monitoring docker containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
      # scopes: autoupdate, monitor
      - com.centurylinklabs.watchtower.scope=autoupdate
      # Homer labels
      - "homer.enable=true"
      - "homepage.group=Tools"
      - "homepage.name=Uptime Kuma"
      - "homepage.description=A self-hosted monitoring tool"
      - "homepage.icon=uptime-kuma.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"