---
version: "3"

networks:
  backend:
    external: true 

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.3-r0-ls315
    container_name: qbittorrent
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      # Vuetorrent mod
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
    # build:
      # context: "."
      # For baking theme directly into container
      # dockerfile_inline: |
      #   FROM lscr.io/linuxserver/qbittorrent:4.6.3-libtorrentv1
      #   RUN mkdir /opt/theme \
      #       && cd /opt/theme \
      #       && curl -LJO https://github.com/WDaan/VueTorrent/releases/download/v2.6.0/vuetorrent.zip \
      #       && unzip vuetorrent.zip \
      #       && rm vuetorrent.zip
    volumes:
      # General config location
      - /opt/qbittorrent:/config
      # General downloads location
      - ${MEDIA}/00download:/downloads
      # Music and Betanin ingets integration
      - ${MEDIA}/00music/library/_staging:/music/_staging
      - ./config/done.sh:/opt/done.sh
    ports:
      # - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '512M'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUBDOMAIN}.${ROOT_DOMAIN}`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT}"
      # - "traefik.docker.network=frontend"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=authelia@docker"
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
      # scopes: autoupdate, monitor
      - com.centurylinklabs.watchtower.scope=autoupdate
      # Homer labels
      - "homer.enable=true"
      - "homepage.group=Downloading"
      - "homepage.name=Qbittorrent"
      - "homepage.description=Free and reliable P2P BitTorrent client."
      - "homepage.icon=qbittorrent.png"
      # - homer.priority=2
      - "homer.target=_blank"
      - "homepage.href=https://${SUBDOMAIN}.${ROOT_DOMAIN}"